name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.11.1
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v5.0.0
      with:
        name: golang_api

    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yuripaixao/curso_ci_docker:${{github.ref_name}}
    


